import * as menuConstansts from "./menuConstants";
import * as sectionConstansts from "./sectionConstants";

export const catalogLabelEnum = {
    [menuConstansts.FLOWER_BULBS]: 'Цибулини квітів',
    [menuConstansts.SEEDLINGS_OF_PERENNIALS]: 'Саджанці багаторічників',
    [menuConstansts.FRUIT_SEEDLINGS]: 'Саджанці плодових',
    [menuConstansts.EXOTICS]: 'Екзотика',
    [menuConstansts.TREE_SEEDLINGS]: 'Саджанці дерев',
    [menuConstansts.SEEDLINGS_OF_CONIFEROUS_PLANTS]: 'Саджанці хвойних рослин',
    [menuConstansts.SEEDLINGS_OF_BUSHES]: 'Саджанці кущів',
    [menuConstansts.ROSE_SEEDLINGS]: 'Саджанці троянд',
    [menuConstansts.GROUND_COVER_PLANTS]: 'Ґрунтопокривні рослини',
    [menuConstansts.HOUSEPLANTS]: 'Кімнатні рослини',
    [menuConstansts.SEED]: 'Насіння',
    [menuConstansts.GARDEN_EQUIPMENT]: 'Садовий інвентар',
    [menuConstansts.CHRISTMAS_DECORATIONS]: 'Новорічні прикраси'
}

export const subCatalogLabelEnum = {
    [sectionConstansts.TULIPS]: "Тюльпани",
    [sectionConstansts.DAFFODILS]: "Нарциси",
    [sectionConstansts.HYACINTHS]: "Гіацинти",
    [sectionConstansts.CROCUSES]: "Крокуси",
    [sectionConstansts.ALLIUM]: "Алліум",
    [sectionConstansts.LILIES]: "Лілії",
    [sectionConstansts.FRITILLARIA]: "Фрітіларія",
    [sectionConstansts.MUSCARI]: "Мускарі",
    [sectionConstansts.AMARYLLIS]: "Амариліс",
    [sectionConstansts.ANEMONES]: "Анемони",
    [sectionConstansts.BUTTERCUP]: "Лютики",
    [sectionConstansts.EREMURUS]: "Еремурус",
    [sectionConstansts.CAMASSIA]: "Камассія",
    [sectionConstansts.LATE_BLOOMER]: "Пізньоцвіт",
    [sectionConstansts.DUTCH_IRISES]: "Голландські іриси",
    [sectionConstansts.CHIONODOX]: "Хіонодокса",
    [sectionConstansts.SNOWDROP]: "Підсніжник",
    [sectionConstansts.SNOWFLAKES]: "Проліски",
    [sectionConstansts.PEONIES]: "Півонії",
    [sectionConstansts.HOSTAS]: "Хости",
    [sectionConstansts.PERENNIAL_IRISES]: "Багаторічні іриси",
    [sectionConstansts.DAYLILIES]: "Лілейники",
    [sectionConstansts.SELAGINELLA]: "Селагінела",
    [sectionConstansts.CORNFLOWER]: "Волошка",

    [sectionConstansts.BLACKBERRY]: "Ожина",
    [sectionConstansts.CRANBERRY]: "Журавлина",
    [sectionConstansts.COWBERRY]: "Брусниця",
    [sectionConstansts.HONEYBERRIES]: "Жимолость їстівна",
    [sectionConstansts.RASPBERRY]: "Малина",
    [sectionConstansts.HAZELNUT]: "Фундук",
    [sectionConstansts.GOOSEBERRY]: "Аґрус",
    [sectionConstansts.CURRANT]: "Смородина",
    [sectionConstansts.GOJI_BERRIES]: "Ягоди Годжі",
    [sectionConstansts.GRAPE_SEEDLINGS]: "Саджанці винограду",

    [sectionConstansts.PERSIMMON]: "Хурма",
    [sectionConstansts.FIG]: "Інжир",
    [sectionConstansts.GARNET]: "Гранат",
    [sectionConstansts.KIWI]: "Ківі",
    [sectionConstansts.AVOCADO]: "Авокадо",
    [sectionConstansts.AZIMINA]: "Азіміна",
    [sectionConstansts.PINEAPPLE]: "Ананас",
    [sectionConstansts.ARBUTUS]: "Арбутус",
    [sectionConstansts.BANANA]: "Банан",
    [sectionConstansts.ZISYPHUS]: "Зізіфус",
    [sectionConstansts.EDIBLE_CHESTNUT]: "Каштан їстівний",
    [sectionConstansts.BROOM]: "Помело",
    [sectionConstansts.FEIJOA]: "Фейхоа",

    [sectionConstansts.DWARF_TREES]: "Карликові дерева",
    [sectionConstansts.SEEDLINGS_OF_COLUMNAR]: "Саджанці колоновидних",
    [sectionConstansts.APPLE_SEEDLINGS]: "Саджанці яблуні",
    [sectionConstansts.MULBERRY]: "Шовковиця",
    [sectionConstansts.TURF]: "Дерен",
    [sectionConstansts.PEAR_SEEDLINGS]: "Саджанці груш",
    [sectionConstansts.CHERRY_SEEDLINGS]: "Саджанці вишні",
    [sectionConstansts.MERRY_SEEDLINGS]: "Саджанці черешні",
    [sectionConstansts.PEACH_SEEDLINGS]: "Саджанці персика",
    [sectionConstansts.PLUM_SEEDLINGS]: "Саджанці слив",
    [sectionConstansts.APRICOT_SEEDLINGS]: "Саджанці абрикосу",
    [sectionConstansts.NECTARINE]: "Нектарин",
    [sectionConstansts.ALMOND]: "Мигдаль",
    [sectionConstansts.WALNUT]: "Волоський горіх",

    [sectionConstansts.SPRUCE]: "Ялина",
    [sectionConstansts.CEDAR]: "Кедр",
    [sectionConstansts.CYPRESS]: "Кипарисовик",
    [sectionConstansts.JUNIPER]: "Ялівець",
    [sectionConstansts.FIR]: "Ялиця",
    [sectionConstansts.PINE]: "Сосна",
    [sectionConstansts.YEW]: "Тис",
    [sectionConstansts.WHITE_CEDAR]: "Туя",
    [sectionConstansts.LARCH]: "Модрина",
    [sectionConstansts.CONIFERS_ON_THE_STEM]: "Хвойні на штамбі",

    [sectionConstansts.SPIREA_SEEDLINGS]: "Саджанці спіреї",
    [sectionConstansts.HIBISCUS_SEEDLINGS]: "Саджанці гібіскусу",
    [sectionConstansts.JASMINE_SEEDLINGS]: "Саджанці жасміну",
    [sectionConstansts.WEIGEL_SEEDLINGS]: "Саджанці вейгели",
    [sectionConstansts.BARBARA_SEEDLINGS]: "Саджанці барбарису",
    [sectionConstansts.LILAC_SEEDLINGS]: "Саджанці бузку",
    [sectionConstansts.HYDRANGEA_SEEDLINGS]: "Саджанці гортензії",

    [sectionConstansts.CLIMBING_ROSES]: "Плетисті троянди",
    [sectionConstansts.STANDARD_ROSES]: "Штамбові троянди",
    [sectionConstansts.SETS_OF_ROSES]: "Комплекти троянд",
    [sectionConstansts.FLORIBUNDA_ROSES]: "Троянди флорібунда",
    [sectionConstansts.HYBRID_TEA_ROSES]: "Чайно-гібридні троянди",
    [sectionConstansts.ROSES_MCGRADY]: "Троянди Макгрейді",
    [sectionConstansts.GROUND_COVER_ROSES]: "Ґрунтопокривні троянди",
    [sectionConstansts.SCREWS]: "Шраби",
    [sectionConstansts.PARK_ROSES]: "Паркові троянди",
    [sectionConstansts.BORDER_ROSES]: "Бордюрні троянди",
    [sectionConstansts.WHITE_ROSES]: "Білі троянди",
    [sectionConstansts.RED_ROSES]: "Червоні троянди",
    [sectionConstansts.PINK_ROSES]: "Рожеві троянди",
    [sectionConstansts.YELLOW_ROSES]: "Жовті троянди",
    [sectionConstansts.BLUE_ROSES]: "Сині троянди",

    [sectionConstansts.THREAD_VERONICA]: "Ниткоподібна вероніка",
    [sectionConstansts.CRASSULA]: "Очиток помилковий",
    [sectionConstansts.THYME]: "Чебрець",
    [sectionConstansts.CREEPING_CLOVER]: "Конюшина повзуча",
    [sectionConstansts.KOTULA]: "Котула",
    [sectionConstansts.ZHIVUCHKA]: "Живучка",
    [sectionConstansts.PERIWINKLE]: "Барвінок",
    [sectionConstansts.LAURENTA_RIVER]: "Лаурента річкова",
    [sectionConstansts.MUHLENBECKIA]: "Мюленбекія",

    [sectionConstansts.ORCHIDS]: "Орхідеї",
    [sectionConstansts.INDOOR_DAFFODILS]: "Кімнатні нарциси",
    [sectionConstansts.INDOOR_ROSES]: "Кімнатні троянди",
    [sectionConstansts.INDOOR_CHRYSANTHEMUMS]: "Кімнатні хризантеми",
    [sectionConstansts.BONSAI]: "Бонсай",
    [sectionConstansts.EUCALYPTUS]: "Евкаліпт",
    [sectionConstansts.CACTUS]: "Кактус",
    [sectionConstansts.ALOE]: "Алое",
    [sectionConstansts.FICUS]: "Фікус",

    [sectionConstansts.VEGETABLE_SEEDS]: "Насіння овочів",
    [sectionConstansts.FLOWER_SEEDS]: "Насіння квітів",
    [sectionConstansts.CUCUMBER_SEEDS]: "Насіння огірків",
    [sectionConstansts.TOMATO_SEEDS]: "Насіння помідорів",
    [sectionConstansts.PETUNIA]: "Петунія",
    [sectionConstansts.ANNUAL_CROPS]: "Однорічні культури",
    [sectionConstansts.CELERY_SEEDS]: "Насіння селери",
    [sectionConstansts.CARROT_SEEDS]: "Насіння моркви",
    [sectionConstansts.ONION_SEEDLING]: "Цибуля сіянка",
    [sectionConstansts.MICROGREEN_SEEDS]: "Насіння мікрозелені",
    [sectionConstansts.PEPPER_SEEDS]: "Насіння перцю",
    [sectionConstansts.ASTER_SEEDS]: "Насіння айстри",
    [sectionConstansts.EGGPLAN_SEEDS]: "Насіння баклажанів",
    [sectionConstansts.ZUCCHINI_SEEDS]: "Насіння кабачків",
    [sectionConstansts.SPICE_SEEDS]: "Насіння прянощів",
    [sectionConstansts.CABBAGE_SEEDS]: "Насіння капусти",
    [sectionConstansts.MELON_SEEDS]: "Насіння дині",
    [sectionConstansts.BEET_SEEDS]: "Насіння буряка",
    [sectionConstansts.CORN_SEEDS]: "Насіння кукурудзи",
    [sectionConstansts.LEGUME_SEEDS]: "Насіння бобових",
    [sectionConstansts.VIOLET_SEEDS]: "Насіння фіалки",
    [sectionConstansts.CALENDULA_SEEDS]: "Насіння календули",
    [sectionConstansts.WATERMELON_SEEDS]: "Насіння кавунів",
    [sectionConstansts.POPPY_SEEDS]: "Насіння маків",
    [sectionConstansts.MYCELIUM_OF_MUSHROOMS]: "Міцелій грибів",
    [sectionConstansts.CLOVE_SEEDS]: "Насіння гвоздики",
    [sectionConstansts.DILL_SEEDS]: "Насіння кропу",
    [sectionConstansts.RADISH_SEEDS]: "Насіння редиски",
    [sectionConstansts.BANANA_SEEDS]: "Насіння банану",

    [sectionConstansts.GARDEN_EQUIPMENT]: "Садовий інвентар",
    [sectionConstansts.BASKET_FOR_BULBS]: "Кошик для цибулин",
    [sectionConstansts.PLANT_PROTECTION_PRODUCTS]: "Засоби захисту рослин",
    [sectionConstansts.SUBSTRATES_AND_PEAT]: "Субстрати і торф",
    [sectionConstansts.COMPOSTING_PREPARATIONS]: "Препарати для компостування",
    [sectionConstansts.GREENHOUSES]: "Теплиці і парники",
    [sectionConstansts.ACCESSORIES]: "Аксесуари",
    [sectionConstansts.HYDROGEL]: "Гідрогель",
    [sectionConstansts.GROWING_POTS]: "Горщики для вирошування",
    [sectionConstansts.PLANTING_KITS]: "Комплекти для посадки",

    [sectionConstansts.GARLANDS]: "Гірлянди",
    [sectionConstansts.CANDLES]: "Свічки",
    [sectionConstansts.NEW_YEAR_FIGURES]: "Фігури новорічні",
    [sectionConstansts.NEW_YEAR_PENDANTS]: "Підвіски новорічні",
    [sectionConstansts.CANDLESTICKS]: "Підсвічники",
    [sectionConstansts.NECKLACES_FOR_CHRISTMAS_TREE]: "Намиста на ялинку",
    [sectionConstansts.NEW_YEAR_RAIN]: "Новорічний дощик",
    [sectionConstansts.NEW_YEAR_DECORATION]: "Новорічна декорація"
}

export const catalogOrderEnum = {
    [menuConstansts.FLOWER_BULBS]: 1,
    [menuConstansts.SEEDLINGS_OF_PERENNIALS]: 2,
    [menuConstansts.FRUIT_SEEDLINGS]: 3,
    [menuConstansts.EXOTICS]: 4,
    [menuConstansts.TREE_SEEDLINGS]: 5,
    [menuConstansts.SEEDLINGS_OF_CONIFEROUS_PLANTS]: 6,
    [menuConstansts.SEEDLINGS_OF_BUSHES]: 7,
    [menuConstansts.ROSE_SEEDLINGS]: 8,
    [menuConstansts.GROUND_COVER_PLANTS]: 9,
    [menuConstansts.HOUSEPLANTS]: 10,
    [menuConstansts.SEED]: 11,
    [menuConstansts.GARDEN_EQUIPMENT]: 12,
    [menuConstansts.CHRISTMAS_DECORATIONS]: 13
}

export const subCatalogEnum = {
    [menuConstansts.FLOWER_BULBS]: [
        sectionConstansts.TULIPS,
        sectionConstansts.DAFFODILS,
        sectionConstansts.HYACINTHS,
        sectionConstansts.CROCUSES,
        sectionConstansts.ALLIUM,
        sectionConstansts.LILIES,
        sectionConstansts.FRITILLARIA,
        sectionConstansts.MUSCARI,
        sectionConstansts.AMARYLLIS,
        sectionConstansts.ANEMONES,
        sectionConstansts.BUTTERCUP,
        sectionConstansts.EREMURUS,
        sectionConstansts.CAMASSIA,
        sectionConstansts.LATE_BLOOMER,
        sectionConstansts.DUTCH_IRISES,
        sectionConstansts.CHIONODOX,
        sectionConstansts.SNOWDROP,
        sectionConstansts.SNOWFLAKES],

    [menuConstansts.SEEDLINGS_OF_PERENNIALS]: [
        sectionConstansts.PEONIES,
        sectionConstansts.HOSTAS,
        sectionConstansts.PERENNIAL_IRISES,
        sectionConstansts.DAYLILIES,
        sectionConstansts.SELAGINELLA,
        sectionConstansts.CORNFLOWER],

    [menuConstansts.FRUIT_SEEDLINGS]: [
        sectionConstansts.BLACKBERRY,
        sectionConstansts.CRANBERRY,
        sectionConstansts.COWBERRY,
        sectionConstansts.HONEYBERRIES,
        sectionConstansts.RASPBERRY,
        sectionConstansts.HAZELNUT,
        sectionConstansts.GOOSEBERRY,
        sectionConstansts.CURRANT,
        sectionConstansts.GOJI_BERRIES,
        sectionConstansts.GRAPE_SEEDLINGS],

    [menuConstansts.EXOTICS]: [
        sectionConstansts.PERSIMMON,
        sectionConstansts.FIG,
        sectionConstansts.GARNET,
        sectionConstansts.KIWI,
        sectionConstansts.AVOCADO,
        sectionConstansts.AZIMINA,
        sectionConstansts.PINEAPPLE,
        sectionConstansts.ARBUTUS,
        sectionConstansts.BANANA,
        sectionConstansts.ZISYPHUS,
        sectionConstansts.EDIBLE_CHESTNUT,
        sectionConstansts.BROOM,
        sectionConstansts.FEIJOA],

    [menuConstansts.TREE_SEEDLINGS]: [
        sectionConstansts.DWARF_TREES,
        sectionConstansts.SEEDLINGS_OF_COLUMNAR,
        sectionConstansts.APPLE_SEEDLINGS,
        sectionConstansts.MULBERRY,
        sectionConstansts.TURF,
        sectionConstansts.PEAR_SEEDLINGS,
        sectionConstansts.CHERRY_SEEDLINGS,
        sectionConstansts.MERRY_SEEDLINGS,
        sectionConstansts.PEACH_SEEDLINGS,
        sectionConstansts.PLUM_SEEDLINGS,
        sectionConstansts.APRICOT_SEEDLINGS,
        sectionConstansts.NECTARINE,
        sectionConstansts.ALMOND,
        sectionConstansts.WALNUT],

    [menuConstansts.SEEDLINGS_OF_CONIFEROUS_PLANTS]: [
        sectionConstansts.SPRUCE,
        sectionConstansts.CEDAR,
        sectionConstansts.CYPRESS,
        sectionConstansts.JUNIPER,
        sectionConstansts.FIR,
        sectionConstansts.PINE,
        sectionConstansts.YEW,
        sectionConstansts.WHITE_CEDAR,
        sectionConstansts.LARCH,
        sectionConstansts.CONIFERS_ON_THE_STEM],

    [menuConstansts.SEEDLINGS_OF_BUSHES]: [
        sectionConstansts.SPIREA_SEEDLINGS,
        sectionConstansts.HIBISCUS_SEEDLINGS,
        sectionConstansts.JASMINE_SEEDLINGS,
        sectionConstansts.WEIGEL_SEEDLINGS,
        sectionConstansts.BARBARA_SEEDLINGS,
        sectionConstansts.LILAC_SEEDLINGS,
        sectionConstansts.HYDRANGEA_SEEDLINGS],

    [menuConstansts.ROSE_SEEDLINGS]: [
        sectionConstansts.CLIMBING_ROSES,
        sectionConstansts.STANDARD_ROSES,
        sectionConstansts.SETS_OF_ROSES,
        sectionConstansts.FLORIBUNDA_ROSES,
        sectionConstansts.HYBRID_TEA_ROSES,
        sectionConstansts.ROSES_MCGRADY,
        sectionConstansts.GROUND_COVER_ROSES,
        sectionConstansts.SCREWS,
        sectionConstansts.PARK_ROSES,
        sectionConstansts.BORDER_ROSES,
        sectionConstansts.WHITE_ROSES,
        sectionConstansts.RED_ROSES,
        sectionConstansts.PINK_ROSES,
        sectionConstansts.YELLOW_ROSES,
        sectionConstansts.BLUE_ROSES],

    [menuConstansts.GROUND_COVER_PLANTS]: [
        sectionConstansts.THREAD_VERONICA,
        sectionConstansts.CRASSULA,
        sectionConstansts.THYME,
        sectionConstansts.CREEPING_CLOVER,
        sectionConstansts.KOTULA,
        sectionConstansts.ZHIVUCHKA,
        sectionConstansts.PERIWINKLE,
        sectionConstansts.LAURENTA_RIVER,
        sectionConstansts.MUHLENBECKIA],

    [menuConstansts.HOUSEPLANTS]: [
        sectionConstansts.ORCHIDS,
        sectionConstansts.INDOOR_DAFFODILS,
        sectionConstansts.INDOOR_ROSES,
        sectionConstansts.INDOOR_CHRYSANTHEMUMS,
        sectionConstansts.BONSAI,
        sectionConstansts.EUCALYPTUS,
        sectionConstansts.CACTUS,
        sectionConstansts.ALOE,
        sectionConstansts.FICUS],

    [menuConstansts.SEED]: [
        sectionConstansts.VEGETABLE_SEEDS,
        sectionConstansts.FLOWER_SEEDS,
        sectionConstansts.CUCUMBER_SEEDS,
        sectionConstansts.TOMATO_SEEDS,
        sectionConstansts.PETUNIA,
        sectionConstansts.ANNUAL_CROPS,
        sectionConstansts.CELERY_SEEDS,
        sectionConstansts.CARROT_SEEDS,
        sectionConstansts.ONION_SEEDLING,
        sectionConstansts.MICROGREEN_SEEDS,
        sectionConstansts.PEPPER_SEEDS,
        sectionConstansts.ASTER_SEEDS,
        sectionConstansts.EGGPLAN_SEEDS,
        sectionConstansts.ZUCCHINI_SEEDS,
        sectionConstansts.SPICE_SEEDS,
        sectionConstansts.CABBAGE_SEEDS,
        sectionConstansts.MELON_SEEDS,
        sectionConstansts.BEET_SEEDS,
        sectionConstansts.CORN_SEEDS,
        sectionConstansts.LEGUME_SEEDS,
        sectionConstansts.VIOLET_SEEDS,
        sectionConstansts.CALENDULA_SEEDS,
        sectionConstansts.WATERMELON_SEEDS,
        sectionConstansts.POPPY_SEEDS,
        sectionConstansts.MYCELIUM_OF_MUSHROOMS,
        sectionConstansts.CLOVE_SEEDS,
        sectionConstansts.DILL_SEEDS,
        sectionConstansts.RADISH_SEEDS,
        sectionConstansts.BANANA_SEEDS],

    [menuConstansts.GARDEN_EQUIPMENT]: [
        sectionConstansts.GARDEN_EQUIPMENT,
        sectionConstansts.BASKET_FOR_BULBS,
        sectionConstansts.PLANT_PROTECTION_PRODUCTS,
        sectionConstansts.SUBSTRATES_AND_PEAT,
        sectionConstansts.COMPOSTING_PREPARATIONS,
        sectionConstansts.GREENHOUSES,
        sectionConstansts.ACCESSORIES,
        sectionConstansts.HYDROGEL,
        sectionConstansts.GROWING_POTS,
        sectionConstansts.PLANTING_KITS],

    [menuConstansts.CHRISTMAS_DECORATIONS]: [
        sectionConstansts.GARLANDS,
        sectionConstansts.CANDLES,
        sectionConstansts.NEW_YEAR_FIGURES,
        sectionConstansts.NEW_YEAR_PENDANTS,
        sectionConstansts.CANDLESTICKS,
        sectionConstansts.NECKLACES_FOR_CHRISTMAS_TREE,
        sectionConstansts.NEW_YEAR_RAIN,
        sectionConstansts.NEW_YEAR_DECORATION]
}